### ISSUE TITLE
Plans for including data from `D to Z`?

### ISSUE THREAD

**Issue by Dawny33** [JuliaQuant/MarketData.jl#22]
(With reference to #13 )

Is there a document or a plan for the datasets from `D` to `Z`?

If yes, then maybe I can help with it.

**Comment by milktrader** [comment]
Well I was thinking DOW, EK, F, GM that sort of thing .... by all means chip in!

**Comment by Dawny33** [comment]
Great!  Is there a document from where I can know about the selection of datasets, which I can use as a reference?

**Comment by milktrader** [comment]
Yes, to sanitize the data against licensing infractions, I've adopted the Quandl free open-source data sets as the source, which they license without restriction.

**Comment by milktrader** [comment]
I thought I had documented where the data was coming from, but maybe not. In any case, here is a (link)[https://www.quandl.com/data/WIKI]

**Comment by Dawny33** [comment]
Would `DELL` on that list be a good choice for `D`?  [Link](https://www.quandl.com/data/WIKI/DELL-Dell-Inc-DELL-Prices-Dividends-Splits-and-Trading-Volume)

Or did I understand your comment wrong?

**Comment by milktrader** [comment]
Sure

**Comment by Dawny33** [comment]
Updated with the Dell Inc's(DELL) data here: https://github.com/JuliaQuant/MarketData.jl/pull/24

**Comment by milktrader** [comment]
- [ ] DELL
- [ ] EK
- [ ] F
- [ ] GM

**Comment by Dawny33** [comment]
Coming to E, `EBAY` looks good enough with time range from `1998 - 2016`.  Sounds good?

**Comment by milktrader** [comment]
Ok, sounds good. Some housekeeping notes not previously mentioned.

I've had previously stopped the data sets on 12-31-2013 so we should probably stay with that plan for consistency. These data sets are for testing and some basic research, but not suitable for more rigorous research where up-to-date data is crucial. Can you change DELL to stop on this date with the next PR? Also, the tests will need to be modified to reflect this.

**Comment by Dawny33** [comment]
Fair enough. Would fix that for `DELL` and `EBAY` in the next PR :+1:

**Comment by milktrader** [comment]
I think after `F` and `GM` we should close this issue.
