### ISSUE TITLE
Intraday sample data

### ISSUE THREAD

**Issue by femtotrader** [JuliaQuant/MarketData.jl#30]
Some intraday sample data (with 1 minute, 5 minutes, 15 minutes or 30 minutes timeframe) will be nice.

**Comment by milktrader** [comment]
`datetime1` and `datetime2` are available now, but they are small samples for testing purposes only. 

To add more extensive data sets we need open source data that has a generous licensing. This is how the current data sets are constructed.

**Comment by femtotrader** [comment]
I was expecting more data to show resampling.
I understand the problem of licensing.

**Comment by milktrader** [comment]
I'll leave this open. There are two possible solutions.

1. Find a liberal licensing source and introduce the data into the package.
2. Solve the random time series issue and use it to create a random DateTime data set with a given seed (ie, so it's always the same)

**Comment by iblis17** [comment]
@milktrader 
There is some pulic data from Taiwan Futures Exchange, it available at here:
 http://www.taifex.com.tw/eng/eng3/eng3_1_3.asp
It's tick data, and need some effort to build candlestick.
The most populare future is `TX`.

**Comment by iblis17** [comment]
Closed by #33
