### ISSUE TITLE
Support Yahoo finance and FRED APIs

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/MarketData.jl#31]
No reason not to have basic support for market data from these sources.

**Comment by iblis17** [comment]
FYI: https://developer.yahoo.com/yql/

**Comment by milktrader** [comment]
I had long ago implemented support for these APIs (not this package though). The functions were called `yahoo` and `fred`. Just something to do at some point.

**Comment by juliohm** [comment]
I am trying to use the `yahoo()` API but it is returning a DNS error, is this a known issue?

>DNSError: ichart.yahoo.com, unknown node or service (EAI_NONAME)

**Comment by juliohm** [comment]
Ok, bad news, the service was terminated:

https://github.com/c0redumb/yahoo_quote_download

**Comment by iblis17** [comment]
Fixed by #62
