### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaQuant/MarketData.jl#34]
There is a typo in http://marketdata.readthedocs.io/en/latest/getting_started.html in it "packages" is misspelt as "pacakges" but in the Github version https://github.com/JuliaQuant/MarketData.jl/blob/master/docs/source/getting_started.rst it is proper so how should I fix it?

**Comment by iblis17** [comment]
ReadTheDocs is an external service. @milktrader may have the permission to check the doc build.
