### ISSUE TITLE
Doc haven't been updated

### ISSUE THREAD

**Issue by femtotrader** [JuliaQuant/MarketData.jl#97]
Hello,

https://juliaquant.github.io/MarketData.jl/stable/test_data/

doesn't reflect latest content of

https://github.com/JuliaQuant/MarketData.jl/blob/master/docs/src/test_data.md

("Random" paragraph is not displayed)

Kind regards

**Comment by femtotrader** [comment]
Lastdeployed on Jun 21, 2022 according
https://github.com/JuliaQuant/MarketData.jl/deployments/github-pages

**Comment by femtotrader** [comment]
`master` branch have been renamed `main` (#92)
but now CI https://github.com/JuliaQuant/MarketData.jl/actions/runs/8858581962/job/24327392839 displays

```
┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaQuant/MarketData.jl" occurs in repo="github.com/JuliaQuant/MarketData.jl.git"
│ - ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push"
│ - ✘ ENV["GITHUB_REF"] matches devbranch="master"
│ - ✔ ENV["GITHUB_ACTOR"] exists
│ - ✔ ENV["DOCUMENTER_KEY"] exists exists
└ Deploying: ✘
```

I think this is a reason for not deploying.

Any idea @iblislin or @Arkoniak what is wrong?

**Comment by femtotrader** [comment]
I forgot to change master to main here
https://github.com/JuliaQuant/MarketData.jl/blob/4e9b9484994123cb3f739e826332eb46f9993298/docs/make.jl#L20
this one is fixed now

I added a DOCUMENTER_KEY as in https://documenter.juliadocs.org/stable/man/hosting/walkthrough/

but https://github.com/JuliaQuant/MarketData.jl/actions/runs/8858747440/job/24327761377

I also tried with generating key with DocumenterTools... but still without good result

https://github.com/JuliaQuant/MarketData.jl/actions/runs/8858747440/job/24328505084

I'm giving up (at least today)

**Comment by iblislin** [comment]
@femtotrader 

okay, I figured it out: https://github.com/JuliaQuant/MarketData.jl/commit/fe531f5079769a42e6b760874e98cc5a40ccc6f5

- https://juliaquant.github.io/MarketData.jl/dev/

**Comment by femtotrader** [comment]
Thanks @iblislin
